// src/lib/ExeInputVisualizer.svelte
<script lang="ts">
  import { toUnicodeChar } from "./utils/unicode";

  let {
    input,
    nextInputIdx,
    isTextMode,
  }: {
    input: number[];
    nextInputIdx: number | null;
    isTextMode: boolean;
  } = $props();

  function valueClass(idx: number) {
    if (nextInputIdx == null) {
      return "";
    } else if (idx === nextInputIdx) {
      return "current-line";
    } else if (idx === nextInputIdx - 1) {
      return "previous-line";
    }
  }
</script>

{#snippet endDisplay()}
  <span class="end-display {valueClass(input.length)}"> END </span>
{/snippet}

{#if isTextMode}
  <p class="text-mode">
    {#each input as val, idx}
      <span class={valueClass(idx)}>{toUnicodeChar(val)}</span>
    {/each}
    {@render endDisplay()}
  </p>
{:else}
  <p>
    {#each input as val, idx}
      <span class={valueClass(idx)}>
        {val}
      </span>{", "}
    {/each}
    {@render endDisplay()}
  </p>
{/if}

<style>
  p.text-mode {
    font-family: monospace;
    font-size: large;
  }

  p.text-mode span {
    white-space: pre;
  }

  .end-display {
    font-size: small;
  }
</style>

// src/app/ExeInputVisualizer.tsx
import { toUnicodeChar } from "./utils/unicode";

export default function ExeInputVisualizer({ input, nextInputIdx, isTextMode }: Props) {
  function getValueStyle(idx: number) {
    if (nextInputIdx == null) {
      return;
    } else if (idx === nextInputIdx) {
      return {
        fontWeight: "bold",
        color: "cyan",
      };
    } else if (idx === nextInputIdx - 1) {
      return {
        color: "lime",
      };
    }
  }


  function endDisplay() {
    return (
      <span style={{
        ...getValueStyle(input.length),
        fontSize: "0.6em",
      }}>
        END
      </span>
    );
  }

  if (isTextMode) {
    return (
      <pre>
        {
          input.map((v, idx) => (
            <span style={getValueStyle(idx)} key={idx}>
              {toUnicodeChar(v)}
            </span>
          ))
        }
        {endDisplay()}
      </pre>
    );
  }
  return <p>
    {
      input.map((v, idx) => (
        <span style={getValueStyle(idx)} key={idx}>{v}, </span>
      ))
    }
    {endDisplay()}
  </p>;
}

interface Props {
  input: number[],
  nextInputIdx: number | null,
  isTextMode: boolean,
}
