// src/lib/CodeGame.svelte
<script lang="ts">
  import ScriptField from "./ScriptField.svelte";
  import ExeOutput from "./ExeOutput.svelte";
  import { type ExeSettings, type ExeState, initExeState, shouldExeContinue } from "./exe/state";
  import { runNextStep, runScript } from "./exe/runner";
  import ScriptVisualizer from "./ScriptVisualizer.svelte";
  import ValueVisualizer from "./ValueVisualizer.svelte";
  import ExeInputField from "./ExeInputField.svelte";
  import { createInputSuccess, type ExeInput, parseInputField } from "./exe/input";
  import ExeInputVisualizer from "./ExeInputVisualizer.svelte";
  import TextModeToggle from "./TextModeToggle.svelte";
  import HelpDialog from "./HelpDialog.svelte";

  let script = $state("");
  let exeInput = $state(createInputSuccess("", []));
  let isStepByStep = $state(false);
  let isExeInputTextMode = $state(false);
  let isExeOutputTextMode = $state(false);
  let exeState: ExeState | null = $state(null);

  function createSettings(): ExeSettings | null {
    if (exeInput.status === "error") {
      return null;
    }
    return {
      maxInstructionCount: 10000,
      cellCount: 16,
      input: exeInput.value,
    };
  }

  function handleToggleExeInputTextMode() {
    const nextIsTextMode = !isExeInputTextMode;
    isExeInputTextMode = nextIsTextMode;
    const nextInput = parseInputField(exeInput.text, nextIsTextMode);
    exeInput = nextInput;
    exeState = null;
  }

  function handleToggleExeOutputTextMode() {
    isExeOutputTextMode = !isExeOutputTextMode;
  }

  function handleExeInputChange(nextInput: ExeInput) {
    exeInput = nextInput;
  }

  function handleScriptChange(newScript: string) {
    script = newScript;
    exeState = null;
  }

  function handleScriptClear() {
    script = "";
    exeState = null;
  }

  function handleRun() {
    const settings = createSettings();
    if (settings == null) {
      return;
    }
    const result = runScript(script, settings);
    exeState = result;
  }

  function handleRunNextStep() {
    if (exeState == null) {
      const settings = createSettings();
      if (settings != null) {
        exeState = initExeState(script, settings);
      }
      return;
    } else if (!shouldExeContinue(exeState)) {
      return;
    }
    runNextStep(exeState);
  }

  function handleToggleStepByStep() {
    isStepByStep = !isStepByStep;
    exeState = null;
  }

  function handleResetExeState() {
    exeState = null;
  }
</script>

<section class="main-section">
  <div class="big-column">
    <h2>JCodeGame</h2>
    <HelpDialog />
    <div>
      <input id="step-by-step-checkbox" type="checkbox" onchange={handleToggleStepByStep} />
      <label class="checkbox-label" for="step-by-step-checkbox"> Step-by-step mode </label>
    </div>

    <h2>Input</h2>
    {#if isStepByStep && exeState != null && exeInput.status === "success"}
      <ExeInputVisualizer
        input={exeInput.value}
        nextInputIdx={exeState?.nextInputIdx ?? 0}
        isTextMode={isExeInputTextMode}
      />
    {:else}
      <TextModeToggle isTextMode={isExeInputTextMode} onToggleTextMode={handleToggleExeInputTextMode} />
      <ExeInputField input={exeInput} isTextMode={isExeInputTextMode} onChange={handleExeInputChange} />
    {/if}

    <h2>Script</h2>
    {#if isStepByStep && exeState != null}
      <ScriptVisualizer {exeState} />
    {:else}
      <ScriptField bind:value={() => script, handleScriptChange} />
    {/if}
    <div class="script-controls">
      <button onclick={handleScriptClear}>✕ Clear</button>
      {#if isStepByStep}
        <button onclick={handleResetExeState}>⏹︎ Reset</button>
        {#if exeState == null || shouldExeContinue(exeState)}
          <button onclick={handleRunNextStep}>⏭︎ Next step</button>
        {:else}
          <button disabled>End</button>
        {/if}
      {:else}
        <button onclick={handleRun}>▶︎ Run</button>
      {/if}
    </div>
  </div>

  <div class="big-column">
    <h2>Output</h2>
    <TextModeToggle isTextMode={isExeOutputTextMode} onToggleTextMode={handleToggleExeOutputTextMode} />
    <ExeOutput output={exeState?.output ?? []} error={exeState?.error ?? null} isTextMode={isExeOutputTextMode} />
    {#if isStepByStep && exeState != null}
      <ValueVisualizer {exeState} />
    {/if}
  </div>
</section>

<style>
  .main-section {
    display: flex;
    flex-direction: row;
    justify-content: center;
    width: 100%;
  }

  .big-column {
    padding-right: 1rem;
    min-width: 310px;
  }

  .checkbox-label {
    padding-left: 5px;
  }

  .script-controls {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    height: 1.75em;
    width: 90%;
  }
</style>

// src/CodeGame.tsx
"use client";

import { FormEvent, useState } from "react";
import ScriptField from "./ScriptField";
import ExeOutput from "./ExeOutput";
import { ExeSettings, ExeState, initExeState, shouldExeContinue } from "./exe/state";
import { runNextStep, runScript } from "./exe/runner";
import ScriptVisualizer from "./ScriptVisualizer";
import ValueVisualizer from "./ValueVisualizer";
import ExeInputField from "./ExeInputField";
import { createInputSuccess, ExeInput, parseInputField } from "./exe/input";
import ExeInputVisualizer from "./ExeInputVisualizer";
import TextModeToggle from "./TextModeToggle";
import HelpDialog from "./HelpDialog";

export default function CodeGame() {
  const [script, setScript] = useState("");
  const [exeInput, setExeInput] = useState(createInputSuccess("", []));
  const [isStepByStep, setIsStepByStep] = useState(false);
  const [isExeInputTextMode, setIsExeInputTextMode] = useState(false);
  const [isExeOutputTextMode, setIsExeOutputTextMode] = useState(false);
  const [exeState, setExeState] = useState<ExeState | null>(null);

  function createSettings(): ExeSettings | null {
    if (exeInput.status === "error") {
      return null;
    }
    return {
      maxInstructionCount: 10000,
      cellCount: 16,
      input: exeInput.value,
    };
  }

  function handleToggleExeInputTextMode() {
    const nextIsTextMode = !isExeInputTextMode;
    setIsExeInputTextMode(nextIsTextMode);
    const nextInput = parseInputField(exeInput.text, nextIsTextMode);
    setExeInput(nextInput);
    setExeState(null);
  }

  function handleToggleExeOutputTextMode() {
    setIsExeOutputTextMode(!isExeOutputTextMode);
  }

  function handleExeInputChange(nextInput: ExeInput) {
    setExeInput(nextInput);
  }

  function handleScriptChange(e: FormEvent<HTMLTextAreaElement>) {
    setScript(e.currentTarget.value);
    setExeState(null);
  }

  function handleScriptClear() {
    setScript("");
    setExeState(null);
  }

  function handleRun() {
    const settings = createSettings();
    if (settings == null) {
      return;
    }
    const result = runScript(script, settings);
    setExeState(result);
  }

  function handleRunNextStep() {
    if (exeState == null) {
      const settings = createSettings();
      if (settings != null) {
        setExeState(initExeState(script, settings));
      }
      return;
    } else if (!shouldExeContinue(exeState)) {
      return;
    }
    const newExeState = structuredClone(exeState);
    runNextStep(newExeState);
    setExeState(newExeState);
  }

  function handleToggleStepByStep() {
    setIsStepByStep(!isStepByStep);
    setExeState(null);
  }

  function handleResetExeState() {
    setExeState(null);
  }

  return (
    <section className="flex flex-row w-full justify-center">
      <div className="pr-[1rem]">
      <h2>JCodeGame</h2>
      <HelpDialog />
        <div>
          <input
            name="stepByStepCheckbox"
            type="checkbox"
            onChange={handleToggleStepByStep}
          />
          <label className="pl-[5px]" htmlFor="stepByStepCheckbox">
            Step-by-step mode
          </label>
        </div>
        <h2>Input</h2>
        {
          isStepByStep && exeState != null && exeInput.status === "success"
            ? <ExeInputVisualizer
              input={exeInput.value}
              nextInputIdx={exeState?.nextInputIdx ?? 0}
              isTextMode={isExeInputTextMode}
            />
            : <>
              <TextModeToggle
                isTextMode={isExeInputTextMode}
                onToggleTextMode={handleToggleExeInputTextMode}
              />
              <ExeInputField
                input={exeInput}
                isTextMode={isExeInputTextMode}
                onChange={handleExeInputChange}
              />
            </>
        }
        <h2>Script</h2>
        {
          isStepByStep && exeState != null
            ? <ScriptVisualizer exeState={exeState} />
            : <ScriptField value={script} onChange={handleScriptChange} />
        }
        <div className="flex flex-row justify-between">
          <button onClick={handleScriptClear}>✕ Clear</button>
          {
            isStepByStep
              ? <>
                <button onClick={handleResetExeState}>⏹︎ Reset</button>
                {
                  exeState == null || shouldExeContinue(exeState)
                    ? <button onClick={handleRunNextStep}>⏭︎ Next step</button>
                    : <button disabled>End</button>
                }
              </>
              : <button onClick={handleRun}>▶︎ Run</button>
          }
        </div>
      </div>
      <div className="pl-[1rem]">
        <h2>Output</h2>
        <TextModeToggle
          isTextMode={isExeOutputTextMode}
          onToggleTextMode={handleToggleExeOutputTextMode}
        />
        <ExeOutput
          output={exeState?.output ?? []}
          error={exeState?.error ?? null}
          isTextMode={isExeOutputTextMode}
        />
        {isStepByStep && exeState != null && <ValueVisualizer exeState={exeState} />}
      </div>
    </section>
  );
}
